$('.owl-carousel-mostOwl').owlCarousel({
    loop:false,
    margin:10,
    nav:true,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1250:{
            items:3
        }
    }
})